const { DataTypes } = require('sequelize');
module.exports = (sequelize) => sequelize.define('Contract', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  contract_no: { type: DataTypes.STRING(50), unique: true, comment: '合同编号' },
  date: { type: DataTypes.DATEONLY, comment: '日期' },
  name: { type: DataTypes.STRING(200), allowNull: false, comment: '合同名称' },
  project_id: { type: DataTypes.INTEGER, comment: '项目ID' },
  project_name: { type: DataTypes.STRING(200), comment: '项目名称' },
  customer_id: { type: DataTypes.INTEGER, comment: '客户ID' },
  customer_name: { type: DataTypes.STRING(100), comment: '客户名称' },
  service_content: { type: DataTypes.TEXT, comment: '服务内容' },
  amount: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '合同金额' },
  receivable: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '应收金额' },
  requested: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '请款金额' },
  received: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '收款金额' },
  labor_cost: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '劳务费' },
  cost: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '成本金额' },
  tax: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '税费' },
  other: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '其他' },
  business_fee: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '业务费' },
  performance: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '绩效' },
  profit: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '利润' },
  manager: { type: DataTypes.STRING(50), comment: '负责人' },
  salesman_id: { type: DataTypes.INTEGER, comment: '业务员ID' },
  salesman: { type: DataTypes.STRING(50), comment: '业务员' },
  attachment: { type: DataTypes.STRING(500), comment: '项目附件' },
  dept_id: { type: DataTypes.INTEGER, comment: '部门ID' },
  dept_name: { type: DataTypes.STRING(50), comment: '部门名称' },
  company_id: { type: DataTypes.INTEGER, comment: '公司ID' },
  company_name: { type: DataTypes.STRING(100), comment: '公司名称' },
  status: { type: DataTypes.ENUM('待签订','进行中','已完成','已取消'), defaultValue: '待签订', comment: '状态' },
  bank_account: { type: DataTypes.STRING(50), comment: '收款银行账号' },
  bank_name: { type: DataTypes.STRING(100), comment: '开户行名称' },
  settlement_method: { type: DataTypes.STRING(50), comment: '结算方式' },
  bank_account_id: { type: DataTypes.INTEGER, comment: '银行账户ID' },
  bank_account_name: { type: DataTypes.STRING(100), comment: '银行账户名称' },
}, { tableName: 'contracts', timestamps: true, underscored: false });
