const { DataTypes } = require('sequelize');
module.exports = (sequelize) => sequelize.define('Finance', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  finance_no: { type: DataTypes.STRING(50), unique: true, comment: '财务编号' },
  date: { type: DataTypes.DATEONLY, comment: '日期' },
  contract_id: { type: DataTypes.INTEGER, comment: '合同ID' },
  contract_no: { type: DataTypes.STRING(50), comment: '合同编号' },
  order_id: { type: DataTypes.INTEGER, comment: '订单ID' },
  order_no: { type: DataTypes.STRING(50), comment: '订单编号' },
  project_id: { type: DataTypes.INTEGER, comment: '项目ID' },
  project_name: { type: DataTypes.STRING(200), comment: '项目名称' },
  category: { type: DataTypes.STRING(50), comment: '款项类别' },
  description: { type: DataTypes.TEXT, comment: '内容描述' },
  type: { type: DataTypes.ENUM('收入','支出'), defaultValue: '收入', comment: '收支' },
  amount: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '金额' },
  company_id: { type: DataTypes.INTEGER, comment: '公司ID' },
  company_name: { type: DataTypes.STRING(100), comment: '公司名称' },
  customer_id: { type: DataTypes.INTEGER, comment: '客户ID' },
  customer_name: { type: DataTypes.STRING(100), comment: '客户名称' },
  booked: { type: DataTypes.TINYINT, defaultValue: 0, comment: '是否入账' },
  invoice_no: { type: DataTypes.STRING(50), comment: '发票号' },
  attachment: { type: DataTypes.STRING(500), comment: '附件' },
  batch_id: { type: DataTypes.INTEGER, comment: '请款批次ID' },
  batch_no: { type: DataTypes.STRING(50), comment: '请款批次号' },
  receipt_id: { type: DataTypes.INTEGER, comment: '收款记录ID' },
  receipt_no: { type: DataTypes.STRING(50), comment: '收款编号' },
  account_type: { type: DataTypes.STRING(20), comment: '账户类型' },
  source_type: { type: DataTypes.STRING(50), comment: '来源类型' },
  source_id: { type: DataTypes.INTEGER, comment: '来源ID' },
  company_bank_account: { type: DataTypes.STRING(100), comment: '公司银行账号快照' },
  bank_account_id: { type: DataTypes.INTEGER, comment: '银行账户ID' },
  bank_account_name: { type: DataTypes.STRING(100), comment: '银行账户名称' },
}, { tableName: 'finances', timestamps: true, underscored: false });
