const { DataTypes } = require('sequelize');
module.exports = (sequelize) => sequelize.define('Order', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  order_no: { type: DataTypes.STRING(50), unique: true, comment: '订单编号' },
  date: { type: DataTypes.DATEONLY, comment: '订单日期' },
  contract_id: { type: DataTypes.INTEGER, comment: '合同ID' },
  contract_no: { type: DataTypes.STRING(50), comment: '合同编号' },
  project_name: { type: DataTypes.STRING(200), comment: '项目名称' },
  customer_name: { type: DataTypes.STRING(100), comment: '客户名称' },
  business_id: { type: DataTypes.INTEGER, comment: '业务ID' },
  business_category: { type: DataTypes.STRING(50), comment: '业务类别' },
  business_parameter: { type: DataTypes.STRING(100), comment: '业务参数' },
  business_unit: { type: DataTypes.STRING(20), comment: '业务单位' },
  quantity: { type: DataTypes.DECIMAL(15,4), defaultValue: 1, comment: '数量' },
  unit_price: { type: DataTypes.DECIMAL(15,4), defaultValue: 0, comment: '单价' },
  total: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '总价' },
  report_date: { type: DataTypes.DATEONLY, comment: '报告日期' },
  report_no: { type: DataTypes.STRING(50), comment: '报告编号' },
  report_signed: { type: DataTypes.TINYINT, defaultValue: 0, comment: '报告已签收' },
  report_attachment: { type: DataTypes.STRING(500), comment: '报告附件' },
  settlement_fee: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '结算费' },
  performance_fee: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '绩效费' },
  manager: { type: DataTypes.STRING(50), comment: '负责人' },
  salesman_id: { type: DataTypes.INTEGER, comment: '业务员ID' },
  salesman: { type: DataTypes.STRING(50), comment: '业务员' },
  dept_id: { type: DataTypes.INTEGER, comment: '部门ID' },
  dept_name: { type: DataTypes.STRING(50), comment: '部门名称' },
  company_id: { type: DataTypes.INTEGER, comment: '公司ID' },
  company_name: { type: DataTypes.STRING(100), comment: '公司名称' },
  bank_account_id: { type: DataTypes.INTEGER, comment: '银行账户ID' },
  bank_account_name: { type: DataTypes.STRING(100), comment: '银行账户名称' },
  status: { type: DataTypes.ENUM('待审核','已审核','进行中','已完成','已取消'), defaultValue: '待审核', comment: '状态' },
  payment_status: { type: DataTypes.STRING(20), defaultValue: '未请款', comment: '请收款状态' },
  requested_amount: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '累计请款金额' },
  received_amount: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '累计收款金额' },
  performance_amount: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '累计绩效金额' },
  calc_version: { type: DataTypes.INTEGER, defaultValue: 1, comment: '计算版本' },
  is_dirty: { type: DataTypes.TINYINT, defaultValue: 0, comment: '是否存在待处理差异' },
  dirty_reason: { type: DataTypes.TEXT, comment: '差异原因说明' },
  last_recalc_at: { type: DataTypes.DATE, comment: '最近重算时间' },
  reviewed_by: { type: DataTypes.INTEGER, comment: '复核人ID' },
  reviewed_by_name: { type: DataTypes.STRING(50), comment: '复核人姓名' },
  reviewed_at: { type: DataTypes.DATE, comment: '复核时间' },
  remark: { type: DataTypes.TEXT, comment: '备注' },
  perf_generated: { type: DataTypes.TINYINT, defaultValue: 0, comment: '绩效已生成' },
  finance_generated: { type: DataTypes.TINYINT, defaultValue: 0, comment: '财务已生成' },
  finance_booked: { type: DataTypes.TINYINT, defaultValue: 0, comment: '财务已入账' },
  business_project: { type: DataTypes.STRING(255), comment: '业务项目' },
}, { tableName: 'orders', timestamps: true, underscored: false });
