const { DataTypes } = require('sequelize');

module.exports = (sequelize) => sequelize.define('PaymentRequest', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  request_no: { type: DataTypes.STRING(50), unique: true, comment: '请款单号' },
  batch_id: { type: DataTypes.INTEGER, comment: '请款批次ID' },
  batch_no: { type: DataTypes.STRING(50), comment: '请款批次号' },
  date: { type: DataTypes.DATEONLY, comment: '请款日期' },
  order_id: { type: DataTypes.INTEGER, comment: '订单ID' },
  order_no: { type: DataTypes.STRING(50), comment: '订单编号' },
  contract_id: { type: DataTypes.INTEGER, comment: '合同ID' },
  contract_no: { type: DataTypes.STRING(50), comment: '合同编号' },
  project_id: { type: DataTypes.INTEGER, comment: '项目ID' },
  project_no: { type: DataTypes.STRING(50), comment: '项目编号' },
  project_name: { type: DataTypes.STRING(200), comment: '项目名称' },
  customer_id: { type: DataTypes.INTEGER, comment: '客户ID' },
  customer_name: { type: DataTypes.STRING(100), comment: '客户名称' },
  company_id: { type: DataTypes.INTEGER, comment: '公司ID' },
  company_name: { type: DataTypes.STRING(100), comment: '公司名称' },
  dept_id: { type: DataTypes.INTEGER, comment: '部门ID' },
  dept_name: { type: DataTypes.STRING(50), comment: '部门名称' },
  salesman_id: { type: DataTypes.INTEGER, comment: '业务员ID' },
  salesman_name: { type: DataTypes.STRING(50), comment: '业务员名称' },
  request_amount: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '请款金额' },
  received_amount: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '已收金额' },
  snapshot_total: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '订单快照金额' },
  snapshot_settlement_fee: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '快照结算费' },
  snapshot_performance_fee: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '快照绩效费' },
  sort_no: { type: DataTypes.INTEGER, defaultValue: 0, comment: '批次内排序' },
  status: { type: DataTypes.ENUM('草稿','待审核','已审核','已完成','已取消'), defaultValue: '草稿', comment: '状态' },
  remark: { type: DataTypes.TEXT, comment: '备注' },
  approved_by: { type: DataTypes.INTEGER, comment: '审批人ID' },
  approved_by_name: { type: DataTypes.STRING(50), comment: '审批人姓名' },
  approved_at: { type: DataTypes.DATE, comment: '审批时间' },
}, { tableName: 'payment_requests', timestamps: true, underscored: false });
