const { DataTypes } = require('sequelize');
module.exports = (sequelize) => sequelize.define('Performance', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  employee_name: { type: DataTypes.STRING(50), comment: '员工姓名' },
  date: { type: DataTypes.DATEONLY, comment: '日期' },
  amount: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '绩效金额' },
  source: { type: DataTypes.STRING(100), comment: '来源' },
  month: { type: DataTypes.STRING(7), comment: '月份(yyyy-mm)' },
  employee_id: { type: DataTypes.INTEGER, comment: '员工ID' },
  emp_no: { type: DataTypes.STRING(50), comment: '工号' },
  name: { type: DataTypes.STRING(100), comment: '姓名' },
  order_id: { type: DataTypes.INTEGER, comment: '订单ID' },
  order_no: { type: DataTypes.STRING(50), comment: '订单编号' },
  contract_id: { type: DataTypes.INTEGER, comment: '合同ID' },
  contract_no: { type: DataTypes.STRING(50), comment: '合同编号' },
  project_id: { type: DataTypes.INTEGER, comment: '项目ID' },
  project_name: { type: DataTypes.STRING(200), comment: '项目名称' },
  dept_name: { type: DataTypes.STRING(50), comment: '部门' },
  position: { type: DataTypes.STRING(50), comment: '岗位' },
  dept_id: { type: DataTypes.INTEGER, comment: '部门ID' },
  company_id: { type: DataTypes.INTEGER, comment: '公司ID' },
  company_name: { type: DataTypes.STRING(100), comment: '公司名称' },
  sales_amount: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '销售金额' },
  received_amount: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '已收金额' },
  performance_rate: { type: DataTypes.DECIMAL(10,4), defaultValue: 0, comment: '绩效比例' },
  performance_amount: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '绩效金额' },
  status: { type: DataTypes.STRING(20), comment: '状态' },
  remark: { type: DataTypes.TEXT, comment: '备注' },
}, { tableName: 'performance', timestamps: true, underscored: false });
