const { DataTypes } = require('sequelize');
module.exports = (sequelize) => sequelize.define('Project', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  project_no: { type: DataTypes.STRING(50), unique: true, comment: '项目编号' },
  date: { type: DataTypes.DATEONLY, comment: '项目日期' },
  name: { type: DataTypes.STRING(200), allowNull: false, comment: '项目名称' },
  content: { type: DataTypes.TEXT, comment: '项目内容' },
  customer_id: { type: DataTypes.INTEGER, comment: '客户ID' },
  customer_name: { type: DataTypes.STRING(100), comment: '客户名称' },
  dept_id: { type: DataTypes.INTEGER, comment: '部门ID' },
  dept_name: { type: DataTypes.STRING(50), comment: '部门名称' },
  company_id: { type: DataTypes.INTEGER, comment: '公司ID' },
  company_name: { type: DataTypes.STRING(100), comment: '公司名称' },
  manager: { type: DataTypes.STRING(50), comment: '负责人' },
  salesman_id: { type: DataTypes.INTEGER, comment: '业务员ID' },
  salesman: { type: DataTypes.STRING(50), comment: '业务员' },
  amount: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '项目金额' },
  receivable: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '应收' },
  requested: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '已请款' },
  received: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '已收款' },
  labor_cost: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '劳务费' },
  cost: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '成本' },
  tax: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '税费' },
  business_fee: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '业务费' },
  other: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '其他' },
  performance: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '绩效' },
  profit: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '利润' },
  status: { type: DataTypes.ENUM('进行中','已完成','已取消'), defaultValue: '进行中', comment: '状态' },
  remark: { type: DataTypes.TEXT, comment: '备注' },
}, { tableName: 'projects', timestamps: true, underscored: false });
