const { DataTypes } = require('sequelize');

module.exports = (sequelize) => sequelize.define('Receipt', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  receipt_no: { type: DataTypes.STRING(50), unique: true, comment: '收款编号' },
  date: { type: DataTypes.DATEONLY, comment: '收款日期' },
  batch_id: { type: DataTypes.INTEGER, comment: '请款批次ID' },
  batch_no: { type: DataTypes.STRING(50), comment: '请款批次号' },
  contract_id: { type: DataTypes.INTEGER, comment: '合同ID' },
  contract_no: { type: DataTypes.STRING(50), comment: '合同编号' },
  project_id: { type: DataTypes.INTEGER, comment: '项目ID' },
  project_name: { type: DataTypes.STRING(200), comment: '项目名称' },
  customer_id: { type: DataTypes.INTEGER, comment: '客户ID' },
  customer_name: { type: DataTypes.STRING(100), comment: '客户名称' },
  company_id: { type: DataTypes.INTEGER, comment: '公司ID' },
  company_name: { type: DataTypes.STRING(100), comment: '公司名称' },
  dept_id: { type: DataTypes.INTEGER, comment: '部门ID' },
  dept_name: { type: DataTypes.STRING(50), comment: '部门名称' },
  salesman_id: { type: DataTypes.INTEGER, comment: '业务员ID' },
  salesman_name: { type: DataTypes.STRING(50), comment: '业务员名称' },
  bank_account_id: { type: DataTypes.INTEGER, comment: '银行账户ID' },
  bank_account_name: { type: DataTypes.STRING(100), comment: '银行账户名称' },
  account_type: { type: DataTypes.STRING(20), defaultValue: '银行', comment: '账户类型' },
  planned_amount: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '应收参考金额' },
  actual_amount: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '实际收款金额' },
  discount_amount: { type: DataTypes.DECIMAL(15,2), defaultValue: 0, comment: '折扣金额' },
  status: { type: DataTypes.STRING(20), defaultValue: '已确认', comment: '状态' },
  remark: { type: DataTypes.TEXT, comment: '备注' },
}, { tableName: 'receipts', timestamps: true, underscored: false });
